In [145]:
import pandas as pd
import numpy as np


In [146]:
Titanic_Train = pd.read_csv('train.csv')

In [147]:
Titanic_Train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [148]:
Titanic_Train.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [149]:
Titanic_Train.drop(['PassengerId','Name','Ticket'],inplace=True,axis=1)

In [150]:
Titanic_Train.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [151]:
Titanic_Train.drop(['Cabin'],inplace=True,axis=1)

In [152]:
Titanic_Train.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [153]:
from  sklearn import preprocessing

In [154]:
Gender = preprocessing.LabelEncoder()
Embarked = preprocessing.LabelEncoder()

In [194]:
sex = Gender.fit_transform(Titanic_Train['Sex'])

In [195]:
sex

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,

In [196]:
Embarked_class = Embarked.fit_transform(Titanic_Train['Embarked'])

In [197]:
Embarked_class

array([2, 0, 2, 2, 2, 1, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2, 2,
       1, 2, 2, 2, 0, 2, 1, 2, 0, 0, 1, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0,
       1, 2, 1, 1, 0, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0, 2,
       2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2,
       0, 2, 2, 0, 2, 1, 2, 0, 2, 2, 2, 0, 2, 2, 0, 1, 2, 0, 2, 0, 2, 2,
       2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2, 2,
       0, 2, 2, 2, 0, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 0, 0, 1, 2, 1,
       2, 2, 2, 2, 0, 2, 2, 2, 0, 1, 0, 2, 2, 2, 2, 1, 0, 2, 2, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 2,
       2, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 2, 1, 2, 2, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 0, 2,
       2, 2, 1, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 1, 1,

In [198]:
from sklearn import tree

In [199]:
Titanic_Train.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='object')

In [200]:
Titanic_Train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 8 columns):
Survived    889 non-null int64
Pclass      889 non-null int64
Sex         889 non-null object
Age         889 non-null float64
SibSp       889 non-null int64
Parch       889 non-null int64
Fare        889 non-null float64
Embarked    889 non-null object
dtypes: float64(2), int64(4), object(2)
memory usage: 48.7+ KB


In [201]:
#sex_lbl,test_Titanic["Pclass"],test_Titanic["Age"], test_Titanic["SibSp"], 
#test_Titanic["Parch"], test_Titanic["Fare"],embarked_lbl

In [202]:
model_tree = tree.DecisionTreeClassifier(max_depth=14)

In [203]:
predictors = pd.DataFrame([sex,Embarked_class,Titanic_Train["Pclass"],Titanic_Train["Age"], Titanic_Train["SibSp"],Titanic_Train["Parch"], Titanic_Train["Fare"]]).T

In [204]:
predictors

0    1    2     3    4    5        6
0    1.0  2.0  3.0  22.0  1.0  0.0   7.2500
1    0.0  0.0  1.0  38.0  1.0  0.0  71.2833
2    0.0  2.0  3.0  26.0  0.0  0.0   7.9250
3    0.0  2.0  1.0  35.0  1.0  0.0  53.1000
4    1.0  2.0  3.0  35.0  0.0  0.0   8.0500
..   ...  ...  ...   ...  ...  ...      ...
884  1.0  2.0  2.0  27.0  0.0  0.0  13.0000
885  0.0  2.0  1.0  19.0  0.0  0.0  30.0000
886  0.0  2.0  3.0  45.0  1.0  2.0  23.4500
887  1.0  0.0  1.0  26.0  0.0  0.0  30.0000
888  1.0  1.0  3.0  32.0  0.0  0.0   7.7500

[889 rows x 7 columns]

In [205]:
model_tree.fit(X = predictors,y =Titanic_Train['Survived'])

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=14, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [207]:
with open("DTree1.dot",'w') as f :
    f = tree.export_graphviz(model_tree,feature_names=["sex","Embarked_class","Pclass","Age","SibSp","Parch","Fare"],out_file=f)

In [208]:
model_tree.score

<bound method ClassifierMixin.score of DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=14, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')>

# Model 

Among Female whose p class is either 1,2 and embarked class less than 1.5 and pclass less than 1.5 and further embarked less than equal to  0.5 we have 1 died 42 survied


In [209]:
from sklearn.ensemble import RandomForestClassifier

In [210]:
test_Titanic = pd.read_csv('test.csv')

In [211]:
test_Titanic.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Embarked  
0  34.5      0      0   330911   7.8292        Q  
1  47.0      1      0   363272   7.0000        S  
2  62.0      0      0   240276   9.6875        Q  
3  27.0      0      0   315154   8.6625        S  
4  22.0      1      1  3101298  12.2875        S

In [212]:
test_Titanic.isna().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [213]:
test_Titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 417 entries, 0 to 416
Data columns (total 10 columns):
PassengerId    417 non-null int64
Pclass         417 non-null int64
Name           417 non-null object
Sex            417 non-null object
Age            417 non-null float64
SibSp          417 non-null int64
Parch          417 non-null int64
Ticket         417 non-null object
Fare           417 non-null float64
Embarked       417 non-null object
dtypes: float64(2), int64(4), object(4)
memory usage: 26.1+ KB


In [214]:
test_Titanic.columns

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [215]:
test_Titanic['Pclass'].unique()

array([3, 2, 1], dtype=int64)

In [216]:
sex_lbl = labl.fit_transform(test_Titanic.Sex)
sex_lbl

array([1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,

In [217]:
embarked_lbl = labl.fit_transform(test_Titanic.Embarked)
embarked_lbl

array([1, 2, 1, 2, 2, 2, 1, 2, 0, 2, 2, 2, 2, 2, 2, 0, 1, 0, 2, 0, 0, 2,
       2, 0, 0, 2, 0, 0, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 0, 1, 0, 2, 2, 0, 2, 2, 0, 1, 2, 2, 2, 0, 2, 2, 2, 1, 0, 2,
       1, 2, 0, 2, 1, 2, 2, 0, 0, 0, 2, 2, 2, 1, 0, 2, 2, 2, 1, 0, 1, 2,
       1, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 1, 2, 0, 2, 1, 1, 2, 2,
       0, 1, 0, 1, 2, 0, 0, 2, 0, 2, 2, 1, 0, 2, 1, 2, 2, 1, 2, 2, 2, 0,
       2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2,
       2, 2, 2, 2, 2, 1, 0, 2, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 2, 2,
       0, 2, 0, 2, 0, 2, 1, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2, 2,
       2, 1, 2, 0, 2, 2, 0, 1, 2, 0, 2, 2, 2, 2, 2, 2, 2, 1, 2, 0, 2, 0,
       2, 2, 2, 0, 0, 2, 1, 2, 2, 2, 2, 2, 1, 0, 2, 0, 0, 2, 0, 0, 2, 0,
       2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 0,
       2, 2, 2, 2, 2, 0, 1, 0, 1, 0, 2, 2, 2, 2, 2, 2, 2, 1, 0, 2, 2, 2,
       2, 0, 2, 2, 1, 0, 2, 2, 2, 0, 0, 2, 2, 2, 0,

In [218]:
test_features = pd.DataFrame([sex_lbl,test_Titanic["Pclass"],test_Titanic["Age"], test_Titanic["SibSp"], 
                              test_Titanic["Parch"], test_Titanic["Fare"],embarked_lbl]).T

In [219]:
test_features

0    1     2    3    4         5    6
0    1.0  3.0  34.5  0.0  0.0    7.8292  1.0
1    0.0  3.0  47.0  1.0  0.0    7.0000  2.0
2    1.0  2.0  62.0  0.0  0.0    9.6875  1.0
3    1.0  3.0  27.0  0.0  0.0    8.6625  2.0
4    0.0  3.0  22.0  1.0  1.0   12.2875  2.0
..   ...  ...   ...  ...  ...       ...  ...
412  1.0  3.0  45.0  0.0  0.0    8.0500  2.0
413  0.0  1.0  39.0  0.0  0.0  108.9000  0.0
414  1.0  3.0  38.5  0.0  0.0    7.2500  2.0
415  1.0  3.0  45.0  0.0  0.0    8.0500  2.0
416  1.0  3.0  45.0  1.0  1.0   22.3583  0.0

[417 rows x 7 columns]

In [232]:
test_pred = model_tree.predict(X=test_features)

In [235]:
Predicted_output = pd.DataFrame({"PassengerId": test_Titanic['PassengerId'], 'Survived' : test_pred})

In [236]:
Predicted_output.to_csv("Output.csv", index = False)

In [237]:
model_tree.score(X=predictors, y = Titanic_Train["Survived"])

0.96962879640045

In [239]:
from sklearn.ensemble import RandomForestClassifier

In [240]:
rf_model  = RandomForestClassifier(n_estimators=1000,oob_score=True,max_features=2) 

In [243]:
Titanic_Train['Sex'] = labl.fit_transform(Titanic_Train['Sex'])

In [244]:
Titanic_Train['Embarked'] = labl.fit_transform(Titanic_Train['Embarked'])

In [245]:
Titanic_Train.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [246]:
features = ["Sex","Pclass","Age","SibSp","Parch","Fare","Embarked"]

In [247]:
rf_model.fit(X = Titanic_Train[features], y = Titanic_Train['Survived'])

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features=2,
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=True, random_state=None,
                       verbose=0, warm_start=False)

In [249]:
print("OOb_Score:")
print(rf_model.oob_score_*100)

OOb_Score:
81.10236220472441


In [250]:
for features, imp in zip(features, rf_model.feature_importances_):
    print(features, imp)

Sex 0.26179702617092837
Pclass 0.08679271952971246
Age 0.25531085578686386
SibSp 0.049451562389493595
Parch 0.03873866207738834
Fare 0.2725174734294108
Embarked 0.03539170061620267


# Sex ,Age, Fare

In [305]:
from sklearn import tree

In [306]:
new_model = tree.DecisionTreeClassifier(max_depth=6)

In [307]:
Titanic_Train.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [308]:
Titanic_Train.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='object')

In [325]:
features = ['Sex','Age','Fare' ]

In [326]:
new_model.fit(X= Titanic_Train[features], y= Titanic_Train['Survived'])

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=6, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [328]:
new_model.score(X= Titanic_Train[features], y = Titanic_Train["Survived"])

0.8301462317210349

In [329]:
test_Titanic.describe()

PassengerId      Pclass         Sex         Age       SibSp  \
count   417.000000  417.000000  417.000000  417.000000  417.000000   
mean   1100.635492    2.263789    0.635492   33.237410    0.448441   
std     120.923774    0.842077    0.481870   13.922884    0.897568   
min     892.000000    1.000000    0.000000    0.170000    0.000000   
25%     996.000000    1.000000    0.000000   23.000000    0.000000   
50%    1101.000000    3.000000    1.000000   32.000000    0.000000   
75%    1205.000000    3.000000    1.000000   45.000000    1.000000   
max    1309.000000    3.000000    1.000000   76.000000    8.000000   

            Parch        Fare    Embarked  
count  417.000000  417.000000  417.000000  
mean     0.393285   35.627188    1.400480  
std      0.982419   55.907576    0.855019  
min      0.000000    0.000000    0.000000  
25%      0.000000    7.895800    1.000000  
50%      0.000000   14.454200    2.000000  
75%      0.000000   31.500000    2.000000  
max      9.000000  512.329200    2.000000

In [330]:
test_Titanic['Sex'] = labl.fit_transform(test_Titanic['Sex'])

In [331]:
test_Titanic['Embarked'] = labl.fit_transform(test_Titanic['Embarked'])

In [332]:
new_Prediction = new_model.predict(X=test_Titanic[features])

In [333]:
Predicted_output = pd.DataFrame({"PassengerId": test_Titanic['PassengerId'], 'Survived' : new_Prediction})

In [334]:
Predicted_output.head()

PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [335]:
with open("AfterRF.dot",'w') as k :
    k = tree.export_graphviz(new_model,feature_names=['Sex','Age','Fare'],out_file=k)