In [115]:
import numpy as np

In [116]:
#create range from 0-9
myarray = np.arange(10)

In [62]:
myarray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
myarray2 = np.random.randint(10,100)

In [19]:
myarray2

65

In [31]:
#creating a random interger with 2x3 matric
myarray3= np.random.random_integers(5, size=(2,3))

c:\users\kobalaji\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  


In [12]:
myarray3

NameError: name 'myarray3' is not defined

In [13]:
B = [1,2,3,4,5,6,7,8,9,10]

In [33]:
B

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [34]:
arr = np.array(B)

In [35]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr.shape

(10,)

In [42]:
arr.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [43]:
arr.shape[0]

IndexError: tuple index out of range

In [46]:
arr.resize(2,5)

In [47]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [48]:
arr.shape[0]

2

In [49]:
arr.shape[1]

5

In [51]:
arr.max()

10

In [76]:
len(arr[0])

5

In [88]:
MyArr = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [89]:
MyArr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
MyArr.shape

(3, 3)

In [91]:
MyArr[1][1]= 22

In [92]:
MyArr

array([[ 1,  2,  3],
       [ 4, 22,  6],
       [ 7,  8,  9]])

In [102]:
k =np.ones((3,3))
k

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [103]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [106]:
np.zeros_like(MyArr)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [107]:
np.ones_like(MyArr)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [169]:
NewArray = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [170]:
NewArray.shape

(3, 5)

In [171]:
Subset_NewArray = NewArray[1:3,:2]

In [172]:
Subset_NewArray

array([[ 6,  7],
       [11, 12]])

In [173]:
Subset_NewArray[1][1]=100

In [174]:
Subset_NewArray

array([[  6,   7],
       [ 11, 100]])

In [175]:
NewArray

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11, 100,  13,  14,  15]])

In [176]:
NewArray[1]

array([ 6,  7,  8,  9, 10])

In [177]:
NewArray[1:3,0:3]

array([[  6,   7,   8],
       [ 11, 100,  13]])

In [178]:
NewArray

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11, 100,  13,  14,  15]])

In [179]:
Subset_NewArray

array([[  6,   7],
       [ 11, 100]])

In [180]:
b2_array =Subset_NewArray[1:]

In [181]:
b2_array

array([[ 11, 100]])

In [182]:
b2_array[0][1] = 55

In [183]:
b2_array

array([[11, 55]])

In [184]:
NewArray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 55, 13, 14, 15]])

In [185]:
Subset_NewArray

array([[ 6,  7],
       [11, 55]])

In [186]:
b2_array

array([[11, 55]])

In [187]:
print(NewArray>2)

[[False False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [189]:
print(NewArray[NewArray>2])

[ 3  4  5  6  7  8  9 10 11 55 13 14 15]


In [194]:
msg = np.array([[1,2],[4,6]])
msg2 = np.array([[2,4],[8,10]])

In [195]:
np.add(msg,msg2)

array([[ 3,  6],
       [12, 16]])

In [196]:
np.subtract(msg,msg2)

array([[-1, -2],
       [-4, -4]])

In [198]:
np.multiply(msg,msg2)

array([[ 2,  8],
       [32, 60]])

In [199]:
np.dot(msg,msg2)

array([[18, 24],
       [56, 76]])

In [204]:
a = np.array([[2,4],[6,8]])
b = np.array([[1,4],[6,0]])

In [205]:
a

array([[2, 4],
       [6, 8]])

In [206]:
b

array([[1, 4],
       [6, 0]])

In [207]:
a*b

array([[ 2, 16],
       [36,  0]])

In [210]:
np.dot(a,b)

array([[26,  8],
       [54, 24]])

In [214]:
c = np.array([[3,1,2],[4,5,6],[7,0,4]])
c

array([[3, 1, 2],
       [4, 5, 6],
       [7, 0, 4]])

In [215]:
d = np.array([[1,6,4],[2,6,0],[1,8,5]])
d

array([[1, 6, 4],
       [2, 6, 0],
       [1, 8, 5]])

In [216]:
np.dot(c,d)

array([[  7,  40,  22],
       [ 20, 102,  46],
       [ 11,  74,  48]])

In [217]:
np.multiply(c,d)

array([[ 3,  6,  8],
       [ 8, 30,  0],
       [ 7,  0, 20]])

In [227]:
v = np.array([[1],[2],[3]])

In [228]:
v.T

array([[1, 2, 3]])

In [229]:
v

array([[1],
       [2],
       [3]])