# 1. Create a 3x3x3 array with random values 

In [219]:
import numpy as np

z = np.random.randint(3,size=(3,3,3))

print(z.shape)
print(z)


(3, 3, 3)
[[[1 1 2]
  [1 0 2]
  [1 2 2]]

 [[2 0 0]
  [1 1 1]
  [2 1 1]]

 [[1 0 0]
  [2 1 1]
  [1 2 0]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [220]:
mat_A = np.zeros((5,5))
mylist = [0,1,2,3,4]
mylist1 = [1,2,3,4,5]
for i in range(len(mat_A)):
    mat_A[i][i] = mylist1[i]

print(mat_A)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [221]:
checkerboard_ones = np.zeros((8,8))

checkerboard_ones[1::2,::2] =1
checkerboard_ones[::2,1:2] =1
checkerboard_ones

array([[0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

# 4. Normalize a 5x5 random matrix

In [222]:
x = np.random.random((5,5))
print("Before\n", x)
xmax ,xmin = x.max(),x.min()
x = (x-xmin)/(xmax-xmin)
print("After\n", x)

Before
 [[0.93083842 0.64085228 0.59168293 0.68519403 0.04420798]
 [0.95086469 0.79256901 0.68778194 0.41537479 0.81636049]
 [0.08342338 0.8167041  0.77918534 0.08884069 0.63709811]
 [0.76431394 0.95790444 0.60624305 0.35972661 0.46688086]
 [0.74840602 0.1287819  0.18657957 0.39076787 0.80001504]]
After
 [[0.97037744 0.65300055 0.5991869  0.70153062 0.        ]
 [0.99229531 0.81904775 0.70436298 0.40622551 0.84508646]
 [0.04291951 0.84546252 0.80439991 0.04884851 0.64889178]
 [0.78812383 1.         0.6151223  0.34532106 0.46259661]
 [0.77071333 0.09256238 0.15581936 0.37929433 0.8271971 ]]


# 5.  How to find common values between two arrays?

In [223]:
matA = np.array([1,4,5,7,3,2])
matB = np.array([9,4,8,7,4,2])

np.intersect1d(matA,matB)

array([2, 4, 7])

# 6.How to get the dates of yesterday, today and tomorrow?

In [224]:
Yesterday = np.datetime64('today',"D")-np.timedelta64(1,"D")
print("Yesterday" ,Yesterday)

today = np.datetime64('today',"D")
print("Today" ,today)

Tomorrow = np.datetime64('today',"D")+np.timedelta64(1,"D")
print("Tomorrow" ,Tomorrow)

Yesterday 2020-07-26
Today 2020-07-27
Tomorrow 2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [225]:
arr_1 = np.random.rand(3,3)
arr_2 = np.random.rand(3,3)
arr_1 == arr_2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [226]:
arr_3 = np.random.random(10)
print("Size is:",arr_3.size)
print("Max is:",arr_3.max())
print("before: \n",arr_3)
for i in range(len(arr_3)):
    if arr_3[i] == arr_3.max():
        arr_3[i] =0
print("After: \n",arr_3)

Size is: 10
Max is: 0.9570699203428422
before: 
 [0.91022206 0.79489323 0.05770502 0.28654693 0.88584428 0.89686993
 0.47917135 0.44060233 0.95706992 0.61387557]
After: 
 [0.91022206 0.79489323 0.05770502 0.28654693 0.88584428 0.89686993
 0.47917135 0.44060233 0.         0.61387557]


# 9. How to print all the values of an array?

In [227]:
for i in range(len(arr_3)):
    print(arr_3[i])

0.9102220550462763
0.7948932303850074
0.05770502333300964
0.2865469305175522
0.8858442782702702
0.8968699278632473
0.4791713480679005
0.4406023286216678
0.0
0.6138755715934274


# 10.Subtract the mean of each row of a matrix

In [228]:
arr1 = np.random.randint(5,size=(3,3))
print(arr1)
mn = arr1.mean()
print(mn)
np.subtract(arr1,mn)

[[4 3 2]
 [3 3 1]
 [4 3 0]]
2.5555555555555554


array([[ 1.44444444,  0.44444444, -0.55555556],
       [ 0.44444444,  0.44444444, -1.55555556],
       [ 1.44444444,  0.44444444, -2.55555556]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [229]:
Z = np.ones(10)
print(Z)
I = np.random.randint(0,len(Z),20)
print(I)
Z += np.bincount(I, minlength=len(Z))


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0 0 0 5 8 1 5 1 3 1 7 3 5 1 6 4 2 0 9 4]


In [230]:
print(Z)

[5. 5. 2. 3. 3. 4. 2. 2. 2. 2.]


# 12.How to get the diagonal of a dot product?

In [231]:
a = np.arange(25).reshape(5,5)
print(a)
print(np.einsum(a, [0,0]))
np.einsum('ii->i',a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
60


array([ 0,  6, 12, 18, 24])

# 13.How to find the most frequent value in an array?

In [232]:
arr2 =np.array([2,3,4,4,3,4,4,5,3])
print(arr2)

print(np.bincount(arr2).argmax())

[2 3 4 4 3 4 4 5 3]
4


# 14.How to get the n largest values of an array

In [243]:
print(arr2.max())
n = 1



5


# 15.How to create a record array from a regular array?

In [234]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
result

rec.array([(1, 'Red', 12.2), (2, 'Green', 15. ), (3, 'White', 20. ),
           (4, 'Orange', 40. )],
          dtype=[('a', '<i4'), ('b', '<U6'), ('c', '<f8')])

In [235]:
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
