In [187]:
import pandas as pd
import numpy as np

In [188]:
Titanic_Data = pd.read_csv('train.csv')

In [189]:
Titanic_Data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [190]:
Titanic_Data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

# First take pclass , gender, SibSP , ParCh, Embarked as dependent variable one by one and others as the independent variable and find the confusion matrix. Using looping or function how can you minimize the code.

In [191]:
from sklearn.model_selection import train_test_split

In [192]:
from sklearn import preprocessing

In [193]:
from sklearn.naive_bayes import GaussianNB

In [194]:
from sklearn.naive_bayes import *

In [195]:
from sklearn.metrics import confusion_matrix

In [196]:
from sklearn.metrics import accuracy_score

In [197]:
Titanic_Data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [198]:
lbl = preprocessing.LabelEncoder()

In [199]:
Titanic_Data['Sex']= lbl.fit_transform(Titanic_Data['Sex'])
Titanic_Data['Embarked']= lbl.fit_transform(Titanic_Data['Embarked'])

In [200]:
x = Titanic_Data[['Pclass', 'Sex', 'SibSp','Embarked']]

In [201]:
y = Titanic_Data[['Survived']]

In [202]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state =2)

In [203]:
print("x_train:",x_train.shape,"\n","y_train:",y_train.shape)

x_train: (711, 4) 
 y_train: (711, 1)


In [204]:
x_train.columns

Index(['Pclass', 'Sex', 'SibSp', 'Embarked'], dtype='object')

In [205]:
y_train.columns

Index(['Survived'], dtype='object')

In [206]:
clf = BernoulliNB()

In [209]:
Y_pred = clf.fit(x_train,y_train).predict(x_test)
Y_pred

c:\users\kobalaji\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0], dtype=int64)

In [210]:
accuracy_score(y_test,Y_pred,normalize=True)

0.8033707865168539

In [211]:
confusion_matrix(y_test,Y_pred)

array([[95, 16],
       [19, 48]], dtype=int64)

In [212]:
Titanic_Data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [213]:
Titanic_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 12 columns):
PassengerId    889 non-null int64
Survived       889 non-null int64
Pclass         889 non-null int64
Name           889 non-null object
Sex            889 non-null int32
Age            889 non-null float64
SibSp          889 non-null int64
Parch          889 non-null int64
Ticket         889 non-null object
Fare           889 non-null float64
Cabin          202 non-null object
Embarked       889 non-null int32
dtypes: float64(2), int32(2), int64(5), object(3)
memory usage: 66.0+ KB


In [214]:
Titanic_Data.drop('Cabin', axis=1,inplace=True)

In [215]:
Titanic_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 11 columns):
PassengerId    889 non-null int64
Survived       889 non-null int64
Pclass         889 non-null int64
Name           889 non-null object
Sex            889 non-null int32
Age            889 non-null float64
SibSp          889 non-null int64
Parch          889 non-null int64
Ticket         889 non-null object
Fare           889 non-null float64
Embarked       889 non-null int32
dtypes: float64(2), int32(2), int64(5), object(2)
memory usage: 62.6+ KB


In [294]:
x = Titanic_Data[['Pclass', 'Sex', 'SibSp','Embarked']]
y = Titanic_Data[['Survived']]

print("x train Columns:",x_train.columns)
print("Y train Columns:",y_train.columns)


x train Columns: Index(['Pclass', 'Sex', 'SibSp', 'Embarked'], dtype='object')
Y train Columns: Index(['Survived'], dtype='object')


In [321]:
NavieBayesAlogrithm(x,y)


Features: Index(['Pclass', 'Sex', 'SibSp', 'Embarked'], dtype='object')
Accuracy_score: 0.8033707865168539
Confusion_Matrix: [[95 16]
 [19 48]]


c:\users\kobalaji\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [322]:
def NavieBayesAlogrithm(x,y):
    clf = BernoulliNB()

    x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state =2)
    Y_pred = clf.fit(x_train,y_train).predict(x_test)
    Accuracy_score = accuracy_score(y_test,Y_pred,normalize=True)
    Confusion_Matrix = confusion_matrix(y_test,Y_pred)
    print("Features:",x_train.columns)
    print("Accuracy_score:",Accuracy_score)
    print("Confusion_Matrix:",Confusion_Matrix) 

# Dependent pclass 

In [323]:
x = Titanic_Data[['Survived', 'Sex', 'SibSp','Embarked']]
y = Titanic_Data[['Pclass']]

print("x train Columns:",x_train.columns)
print("Y train Columns:",y_train.columns)
NavieBayesAlogrithm(x,y)


x train Columns: Index(['Pclass', 'Sex', 'SibSp', 'Embarked'], dtype='object')
Y train Columns: Index(['Survived'], dtype='object')
Features: Index(['Survived', 'Sex', 'SibSp', 'Embarked'], dtype='object')
Accuracy_score: 0.4943820224719101
Confusion_Matrix: [[11  0 31]
 [ 8  0 41]
 [10  0 77]]


c:\users\kobalaji\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


# Dependent Sibsp 

In [325]:
x = Titanic_Data[['Survived', 'Sex', 'Pclass','Embarked']]
y = Titanic_Data[['SibSp']]

print("x train Columns:",x_train.columns)
print("Y train Columns:",y_train.columns)
NavieBayesAlogrithm(x,y)


x train Columns: Index(['Pclass', 'Sex', 'SibSp', 'Embarked'], dtype='object')
Y train Columns: Index(['Survived'], dtype='object')
Features: Index(['Survived', 'Sex', 'Pclass', 'Embarked'], dtype='object')
Accuracy_score: 0.7134831460674157
Confusion_Matrix: [[125   4   0   0   0   0   0]
 [ 31   2   0   0   0   0   0]
 [  6   2   0   0   0   0   0]
 [  4   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0]]


c:\users\kobalaji\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


# Dependent Gender 

In [328]:
x = Titanic_Data[['Survived', 'SibSp', 'Pclass','Embarked']]
y = Titanic_Data[['Sex']]

print("x train Columns:",x_train.columns)
print("Y train Columns:",y_train.columns)
NavieBayesAlogrithm(x,y)


x train Columns: Index(['Pclass', 'Sex', 'SibSp', 'Embarked'], dtype='object')
Y train Columns: Index(['Survived'], dtype='object')
Features: Index(['Survived', 'SibSp', 'Pclass', 'Embarked'], dtype='object')
Accuracy_score: 0.8033707865168539
Confusion_Matrix: [[48 16]
 [19 95]]


c:\users\kobalaji\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


#  Dependent Embarked 

In [329]:
x = Titanic_Data[['Survived', 'SibSp', 'Pclass','Sex']]
y = Titanic_Data[['Embarked']]

print("x train Columns:",x_train.columns)
print("Y train Columns:",y_train.columns)
NavieBayesAlogrithm(x,y)


x train Columns: Index(['Pclass', 'Sex', 'SibSp', 'Embarked'], dtype='object')
Y train Columns: Index(['Survived'], dtype='object')
Features: Index(['Survived', 'SibSp', 'Pclass', 'Sex'], dtype='object')
Accuracy_score: 0.8146067415730337
Confusion_Matrix: [[  0   0  24]
 [  0   0   9]
 [  0   0 145]]


c:\users\kobalaji\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
